name: YasinDev GitHub Auto Commits

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.EMAIL }}"

      - name: Make auto commits
        run: |
          FILE=".github/HACK.md"
          COMMIT_LOOP_COUNT=5  # change to 500+ when ready

          # Ensure file and directory exist
          mkdir -p .github
          touch $FILE

          for ((i=1; i<=COMMIT_LOOP_COUNT; i++)); do
            echo "### Auto Commit #$i" >> $FILE
            date >> $FILE
            echo "Commit number: $i" >> $FILE
            echo "---" >> $FILE

            git add $FILE
            git commit -m "🤖 Auto Commit #$i" || echo "No change to commit"
          done

          # Set remote with token for private repo push
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

          git pull --rebase || echo "No remote changes to pull"
          git push origin HEAD || echo "Push failed"
        env:
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL: ${{ secrets.EMAIL }}
